apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: projectName
  namespace: k8sNameSpace
spec:
  schedule: "30 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          hostAliases:
          - ip: 10.133.0.66
            hostnames:
            - config-reader.remote-admin.intranet
          containers:
            - name: projectName
              image: registry/projectGroup/projectName:tagVersion
              imagePullPolicy: Always
              env:
                - name: JAVA_OPTS
                  value: -Xmx896m -Dfile.encoding=UTF-8 -Duser.country=BR -Duser.language=pt -Duser.Timezone=America/Sao_Paulo  #-javaagent:/opt/newrelic/newrelic.jar -Dnewrelic.config.labels="team:Taipei;slack:#taipei;email:l-investimentos-taipei@uolinc.com;environment:dev;dc:dcenv"
                - name: SPRING_PROFILES_ACTIVE
                  value: tier
              resources:
                limits:
                  memory: 1152Mi
                  cpu: 800m
          restartPolicy: OnFailure
      backoffLimit: 3